# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' get the PCA of a matrix
#'
#' @param x matrix
#' @export
getPCA <- function(matrix) {
    .Call(`_DeltaVelocyto_getPCA`, matrix)
}

#' get the PCA of a matrix
#'
#' @param x matrix
#' @export
testingFunction <- function(dimension) {
    .Call(`_DeltaVelocyto_testingFunction`, dimension)
}

#' get the PCA of a matrix
#'
#' @param x matrix
#' @export
rcpparma_outerproduct <- function(x) {
    .Call(`_DeltaVelocyto_rcpparma_outerproduct`, x)
}

#' get the PCA of a matrix
#'
#' @param x matrix
#' @export
rcpparma_innerproduct <- function(x) {
    .Call(`_DeltaVelocyto_rcpparma_innerproduct`, x)
}

#' get the PCA of a matrix
#'
#' @param x matrix
#' @export
rcpparma_bothproducts <- function(x) {
    .Call(`_DeltaVelocyto_rcpparma_bothproducts`, x)
}

